name: Vulnerability scan

on:
  schedule:
     - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install esp-idf-sbom
        run: pip3 install esp-idf-sbom
      - name: Vulnerability scan
        shell: bash
        env:
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
        run: |
          python3 -m esp_idf_sbom manifest check
          JOB_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          USER_NAME="idf-extra-components"
          if [ $? -eq 0 ]
          then
            MSG=":large_green_circle: No vulnerabilities found"
          else
            MSG=":large_red_circle: New vulnerabilities found"
          fi
          curl --no-progress-meter -i -X POST -H 'Content-Type: application/json'\
               -d "{\"username\": \"${USER_NAME}\", \"text\": \"${MSG} ${JOB_URL}\"}"\
                 "$MATTERMOST_WEBHOOK"
